name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * 0"  # Every Sunday at 00:00 UTC
  push:
    branches:
      - main
      - feat/snake-animation
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: jialanhu0915
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            assets/github-snake.svg
